### ISSUE TITLE
evaluate problem

### ISSUE THREAD

**Issue by lingheng123** [PRBonn/4DMOS#20]
I wanted to evaluate but ran into the following situation. The visualization works normally.
![IMG_4687](https://user-images.githubusercontent.com/88220400/229708311-e7c19f21-0cd8-4495-9024-d63e6eade5da.JPG)

**Comment by benemer** [comment]
It could not find any predictions. What's the content of `/home/robot/4DMOS/predictions/5_scans/poses/labels/strategy_non_overlapping_0.1`?

**Comment by lingheng123** [comment]
![IMG_4688](https://user-images.githubusercontent.com/88220400/229712135-c79adafb-e399-45d4-879c-b8353a00803b.JPG)
![IMG_4689](https://user-images.githubusercontent.com/88220400/229712154-029562ba-2c67-46ff-8f86-cbd100d7384c.JPG)

**Comment by lingheng123** [comment]
when i use  -s test,i could not find any label
![63E6BE237BE68A5F3D4F711F8F221DB1](https://user-images.githubusercontent.com/88220400/229712931-4818a088-976c-4188-ad03-83bec0c1adb1.png)

**Comment by benemer** [comment]
What are the sequences you have in your dataset? And how is your split in `config/semantic-kitti-mos.yaml`?

The default one is

```yaml
split: # sequence numbers
  train:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 9
    - 10
  valid:
    - 8
  test:
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    ```

so these sequences need to be in both the dataset and your predictions when evaluating.
